# Conv2dTranspose with custom kernel

In [1]:
import torch

In [2]:
# Define kernel
kernel = torch.tensor([[0., 1.],
                        [2., 3.]], requires_grad = True)
kernel = kernel[None, None, :, :]
kernel.shape

torch.Size([1, 1, 2, 2])

In [3]:
x = torch.tensor([[[[0., 1.],[2., 3.]]]])
x.shape

torch.Size([1, 1, 2, 2])

In [4]:
convT2d = torch.nn.ConvTranspose2d(1, 1, 2, bias=False)

In [5]:
convT2d.weight

Parameter containing:
tensor([[[[-0.4332,  0.2056],
          [ 0.3706,  0.4683]]]], requires_grad=True)

In [6]:
convT2d.weight.shape

torch.Size([1, 1, 2, 2])

In [7]:
# Replace existing kernel with custom kernel
with torch.no_grad():
   convT2d.weight = torch.nn.Parameter(kernel)

In [8]:
convT2d.weight

Parameter containing:
tensor([[[[0., 1.],
          [2., 3.]]]], requires_grad=True)

In [9]:
convT2d.weight.shape

torch.Size([1, 1, 2, 2])

In [10]:
convT2d(x)

tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<SlowConvTranspose2DBackward>)